openapi: 3.0.0
info:
  description: This API enables the customer to upload file along with metadata 
  version: "1.0.0"
  title: Enterprise Information Archival API
paths:
  /api/v1/upload:
   post:
      security: 
        - basicAuth: []
      operationId: addtoarchive
      responses:
        '200':
          description: 'Uploaded successfully'
        '500':
          description: 'Processing Failed'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '400':
          description: 'Bad Request'
        '503':
          description: 'Service Unavailable'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: upload file
                metadata:
                  $ref: '#/components/schemas/GemFileMetadata'
              required:
                - file
                - metadata
security: 
   - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
  schemas:
    GemFileMetadata:
      type: object
      properties:
        source:
          type: string
          example: DTV-OMS
          description: Name of the source system
        content_type:
          type: string
          example: pdf
          description: Content type of the file to upload All file types are supported
        doc_type:
          type: string
          example: GEM broadband consent
          description: Document refers to the type of the document which is uploaded in the source systems
        retention:
          type: string
          example: yearly
          description: retention policy
        size:
          type: integer
          format: int32
          example: 1084
          description: Size of the file to be uploaded in bytes
        digest:
          type: string
          example: "0b91043ee484abd83c3e4b08d6034d71b937026379f0f59bda6e625e6e214789"
          description: Hash value of digest type specified for the file. The digest make sures that data is encrypted in a secure way
        digest_type:
          type: string
          example: "SHA256"
          description: We support SHA256 digest type for now
        search:
          $ref: '#/components/schemas/SearchItems'
      required:
        - source
        - content_type
        - doc_type
        - retention
        - size
        - digest
        - digest_type
        - search
    SearchItems:
      properties:
        acc_num:
          type: integer
          format: int32
          example: 1277767
          description: Account number
        biller:
          type: string
          example: "STMS"
          description: Biller name
        order_id:
          type: integer
          format: int32
          example: 1005678
          description: Order id
        consent_datetime:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
          description: The datetime captured while consent
        agent_id:
          type: string
          example: "1200238"
          description: Agent id
        agent_type:
          type: string
          example: "call center"
          description: Agent type
        source_system:
          type: string
          example: "DTV-OMS"
          description: Name of the source system
        broadband_status:
          type: string
          example: "system shows connected"
          description: Broadband status
        broadband_consent:
          type: string
          example: "broadband requirement explained"
          description: Broadband consent
      required:
        - biller
        - order_id
        - consent_datetime
        - agent_id
        - agent_type
        - source_system
        - broadband_status
        - broadband_consent
      type: object
